import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const sql = readFileSync(join(__dirname, "..", "..", "supabase", "inquiries.sql"), "utf8");
const fn = (name: string) => new RegExp(`create or replace function ${name}\\([\\s\\S]*?\\$\\$;`).exec(sql)![0];

describe("inquiries.sql", () => {
  it("creates the new tables with RLS on, no policies, closed to the browser roles", () => {
    expect([...sql.matchAll(/create table if not exists (\w+)/g)].map((m) => m[1]))
      .toEqual(["inquiry_messages", "inquiry_attachments", "inquiry_unmatched", "saved_replies", "inquiry_events"]);
    for (const t of ["inquiries", "inquiry_messages", "inquiry_attachments", "inquiry_unmatched", "saved_replies", "inquiry_events"]) {
      expect(sql).toContain(`revoke all on ${t} from anon, authenticated;`);
    }
    for (const t of ["inquiry_messages", "inquiry_attachments", "inquiry_unmatched", "saved_replies", "inquiry_events"]) {
      expect(sql).toContain(`alter table ${t} enable row level security;`);
    }
    expect(sql).not.toMatch(/create policy/i);
  });

  it("adds topic, status, ref, token and the activity columns to inquiries", () => {
    expect(sql).toContain("check (topic in ('order','product','wholesale','account','other'))");
    expect(sql).toContain("check (status in ('new','needs_reply','waiting','closed'))");
    expect(sql).toContain("add column if not exists ref integer generated by default as identity (start with 1001)");
    expect(sql).toContain("create unique index if not exists inquiries_token_idx on inquiries (token)");
    expect(sql).toContain("alter table inquiries alter column kind drop not null;");
    for (const c of ["customer_id", "order_number", "subject", "last_activity_at", "last_customer_at", "waiting_since", "closed_at", "closed_by", "ip_hash", "last_preview", "last_from", "message_count", "file_count"]) {
      expect(sql).toContain(`add column if not exists ${c} `);
    }
  });

  it("backfills old rows: closed up to the seen mark, a first message each", () => {
    expect(sql).toMatch(/then 'closed' else 'new' end[\s\S]*inquiries_seen_at/);
    expect(sql).toMatch(/insert into inquiry_messages \(inquiry_id, direction, source, from_email, body_text, created_at\)[\s\S]*where not exists/);
  });

  it("keeps message ids unique so every inbound write is idempotent", () => {
    expect(sql).toMatch(/ses_message_id\s+text unique/);
    expect(sql).toMatch(/client_key\s+text unique/);
    expect(sql).toMatch(/ses_message_id\s+text not null unique/);
  });

  it("keeps the preview and counters with a trigger on new messages", () => {
    expect(sql).toContain("create trigger inquiry_message_added after insert or update of delivery on inquiry_messages");
    expect(fn("inquiry_message_added")).toContain("new.delivery = 'sending'");
    expect(fn("inquiry_message_added")).toContain("message_count = message_count + 1");
  });

  it("record_inbound_message: duplicate-safe, a plain reply re-opens waiting/closed only", () => {
    const f = fn("record_inbound_message");
    expect(f).toContain("on conflict (ses_message_id) do nothing");
    expect(f).toContain("return 'duplicate'");
    expect(f).toContain("status in ('waiting','closed')");
    expect(f).toContain("set status = 'needs_reply'");
    expect(f).toContain("&& array['auto_reply','spam']");
  });

  it("auto_close_inquiries closes waiting threads older than the cut-off and logs each", () => {
    const f = fn("auto_close_inquiries");
    expect(f).toContain("where status = 'waiting' and waiting_since < p_before");
    expect(f).toContain("'auto_closed'");
  });

  it("functions are security definer, revoked from the browser, granted to service_role", () => {
    for (const name of ["create_inquiry", "record_inbound_message", "auto_close_inquiries"]) {
      expect(fn(name)).toContain("security definer set search_path = public");
      expect(sql).toMatch(new RegExp(`revoke all on function ${name}\\([^)]*\\) from public, anon, authenticated;`));
      expect(sql).toMatch(new RegExp(`grant execute on function ${name}\\([^)]*\\) to service_role;`));
    }
  });

  it("adds a private inquiry-files bucket (images + PDF, 10 MB) and seeds four saved replies", () => {
    expect(sql).toContain("values ('inquiry-files', 'inquiry-files', false, 10485760, array['image/jpeg','image/png','image/heic','image/heif','application/pdf'])");
    expect((sql.match(/^\s*\('(Research use only|Where''s my order|Finding a COA|Wholesale pricing follow-up)/gm) ?? []).length).toBe(4);
  });

  it("logs every module action in inquiry_events", () => {
    for (const a of ["created", "opened", "replied", "closed", "reopened", "auto_closed", "customer_replied", "topic_changed", "linked", "unlinked", "bounced", "reply_saved", "reply_deleted", "unmatched_dismissed", "unmatched_attached"]) {
      expect(sql).toContain(`'${a}'`);
    }
  });
});
