-- supabase/inquiries.sql
-- Admin command center, part 7: Inquiries. Two-way threads: /contact and
-- /wholesale open an inquiry; owner replies go out by email (SES) with a
-- per-thread Reply-To (r-<token>@in.auraprotocols.com); customer replies come
-- back through SES receiving (lib/inquiries/inbound.ts) into inquiry_messages.
-- Run after storefront.sql, accounts-checkout.sql and today.sql. Idempotent.
-- RLS on, no policies: service role only.

-- ---------- 1. inquiries: one row per conversation ----------
alter table inquiries alter column kind drop not null;   -- history only; new rows use topic

alter table inquiries add column if not exists topic text;
update inquiries set topic = case kind when 'wholesale' then 'wholesale' else 'other' end where topic is null;
alter table inquiries alter column topic set default 'other';
alter table inquiries alter column topic set not null;
alter table inquiries drop constraint if exists inquiries_topic_check;
alter table inquiries add constraint inquiries_topic_check check (topic in ('order','product','wholesale','account','other'));

-- Old rows the owner already marked seen on Today are closed; newer ones are new.
alter table inquiries add column if not exists status text;
update inquiries i set status = case when s.inquiries_seen_at is not null and i.created_at <= s.inquiries_seen_at then 'closed' else 'new' end
  from shop_settings s where s.id and i.status is null;
update inquiries set status = 'new' where status is null;
alter table inquiries alter column status set default 'new';
alter table inquiries alter column status set not null;
alter table inquiries drop constraint if exists inquiries_status_check;
alter table inquiries add constraint inquiries_status_check check (status in ('new','needs_reply','waiting','closed'));

alter table inquiries add column if not exists customer_id uuid references customers(id) on delete set null;
alter table inquiries add column if not exists order_number text;
-- "Q-1047" to people. Existing rows are numbered as the column is added.
alter table inquiries add column if not exists ref integer generated by default as identity (start with 1001);
create unique index if not exists inquiries_ref_idx on inquiries (ref);
-- Secret reply-address token (the app makes 32 hex chars from 16 random bytes).
alter table inquiries add column if not exists token text;
update inquiries set token = replace(gen_random_uuid()::text, '-', '') where token is null;
alter table inquiries alter column token set not null;
create unique index if not exists inquiries_token_idx on inquiries (token);
alter table inquiries add column if not exists subject text;
update inquiries set subject = case when kind = 'wholesale' then 'Wholesale inquiry' || coalesce(' — ' || organization, '') else 'Message' end
  where subject is null;
alter table inquiries alter column subject set not null;
alter table inquiries add column if not exists last_activity_at timestamptz;
update inquiries set last_activity_at = created_at where last_activity_at is null;
alter table inquiries alter column last_activity_at set default now();
alter table inquiries alter column last_activity_at set not null;
alter table inquiries add column if not exists last_customer_at timestamptz;   -- the customer's last plain message
update inquiries set last_customer_at = created_at where last_customer_at is null;
alter table inquiries add column if not exists waiting_since timestamptz;      -- set entering waiting; drives auto-close
alter table inquiries add column if not exists closed_at timestamptz;
alter table inquiries add column if not exists closed_by uuid references customers(id) on delete set null;  -- null = automatic
update inquiries i set closed_at = s.inquiries_seen_at from shop_settings s where s.id and i.status = 'closed' and i.closed_at is null;
alter table inquiries add column if not exists ip_hash text;                    -- /contact per-IP limit
alter table inquiries add column if not exists last_preview text;
alter table inquiries add column if not exists last_from text check (last_from in ('customer','owner'));
alter table inquiries add column if not exists message_count integer not null default 0;
alter table inquiries add column if not exists file_count integer not null default 0;
create index if not exists inquiries_open_idx on inquiries (status, last_customer_at);
create index if not exists inquiries_waiting_idx on inquiries (status, waiting_since);
create index if not exists inquiries_activity_idx on inquiries (last_activity_at desc);
create index if not exists inquiries_ip_idx on inquiries (ip_hash, created_at);
create index if not exists inquiries_customer_idx on inquiries (customer_id);
revoke all on inquiries from anon, authenticated;

-- ---------- 2. messages, both directions ----------
create table if not exists inquiry_messages (
  id                  uuid primary key default gen_random_uuid(),
  inquiry_id          uuid not null references inquiries(id) on delete cascade,
  direction           text not null check (direction in ('in','out')),
  source              text not null check (source in ('form','email','admin')),
  from_email          text not null,
  body_text           text not null,            -- new text only (quoted history cut)
  full_text           text,                      -- inbound: the whole text, for "Show full email"
  raw_key             text,                      -- inbound: S3 key of the raw email (deleted after 90 days)
  ses_message_id      text unique,               -- in: SES receipt id (idempotency) · out: SES send id (bounces)
  email_message_id    text,                      -- RFC Message-ID, for In-Reply-To / References
  client_key          text unique,               -- out: one send per reply form, even on a double click
  delivery            text check (delivery in ('sending','sent','delivered','bounced','complained')),
  flags               text[] not null default '{}' check (flags <@ array['auto_reply','spam','other_sender']::text[]),
  dropped_attachments text[] not null default '{}',
  author_id           uuid references customers(id) on delete set null,
  created_at          timestamptz not null default now()
);
create index if not exists inquiry_messages_thread_idx on inquiry_messages (inquiry_id, created_at);
alter table inquiry_messages enable row level security;
revoke all on inquiry_messages from anon, authenticated;

create table if not exists inquiry_attachments (
  id            uuid primary key default gen_random_uuid(),
  message_id    uuid not null references inquiry_messages(id) on delete cascade,
  filename      text not null,
  content_type  text not null,
  size_bytes    integer not null check (size_bytes >= 0),
  storage_path  text not null unique,            -- bucket inquiry-files
  created_at    timestamptz not null default now()
);
create index if not exists inquiry_attachments_message_idx on inquiry_attachments (message_id);
alter table inquiry_attachments enable row level security;
revoke all on inquiry_attachments from anon, authenticated;

-- Inbound mail that matched no thread (bad/old token, or [Q-n] from another address).
create table if not exists inquiry_unmatched (
  id                uuid primary key default gen_random_uuid(),
  ses_message_id    text not null unique,
  from_email        text not null,
  from_name         text,
  to_address        text,
  subject           text not null default '',
  body_text         text not null,
  full_text         text,
  raw_key           text,
  spam              boolean not null default false,
  attachment_names  text[] not null default '{}',
  created_at        timestamptz not null default now(),
  dismissed_at      timestamptz,
  dismissed_by      uuid references customers(id) on delete set null,
  attached_to       uuid references inquiries(id) on delete set null
);
create index if not exists inquiry_unmatched_open_idx on inquiry_unmatched (created_at desc) where dismissed_at is null and attached_to is null;
alter table inquiry_unmatched enable row level security;
revoke all on inquiry_unmatched from anon, authenticated;

create table if not exists saved_replies (
  id          uuid primary key default gen_random_uuid(),
  name        text not null unique check (char_length(name) between 1 and 80),
  body        text not null check (char_length(body) between 1 and 4000),
  updated_at  timestamptz not null default now(),
  updated_by  uuid references customers(id) on delete set null
);
alter table saved_replies enable row level security;
revoke all on saved_replies from anon, authenticated;

-- Thread history and the module's Activity (rows with an actor). inquiry_id is
-- null for saved-reply and unmatched-mail actions.
create table if not exists inquiry_events (
  id          uuid primary key default gen_random_uuid(),
  inquiry_id  uuid references inquiries(id) on delete cascade,
  action      text not null check (action in (
                'created', 'opened', 'replied', 'closed', 'reopened', 'auto_closed', 'customer_replied',
                'topic_changed', 'linked', 'unlinked', 'bounced',
                'reply_saved', 'reply_deleted', 'unmatched_dismissed', 'unmatched_attached')),
  actor       uuid references customers(id) on delete set null,
  detail      text,
  at          timestamptz not null default now()
);
create index if not exists inquiry_events_thread_idx on inquiry_events (inquiry_id, at desc);
create index if not exists inquiry_events_at_idx on inquiry_events (at desc);
alter table inquiry_events enable row level security;
revoke all on inquiry_events from anon, authenticated;

-- ---------- 3. the inquiry's preview and counters follow its messages ----------
-- Auto-replies and spam are stored on the thread but don't become its preview
-- or move the customer's clock.
create or replace function inquiry_message_added() returns trigger
  language plpgsql security definer set search_path = public as $$
declare v_plain boolean := not (new.flags && array['auto_reply','spam']);
begin
  -- An owner reply is claimed with delivery 'sending' before SES is called and
  -- counts only once SES accepted it ('sending' → 'sent'); a failed send
  -- deletes the claim and leaves no trace here.
  if tg_op = 'INSERT' and new.delivery = 'sending' then return new; end if;
  if tg_op = 'UPDATE' and not (old.delivery = 'sending' and new.delivery = 'sent') then return new; end if;
  update inquiries set
    message_count = message_count + 1,
    last_activity_at = greatest(last_activity_at, new.created_at),
    last_preview = case when v_plain then left(regexp_replace(new.body_text, '\s+', ' ', 'g'), 200) else last_preview end,
    last_from = case when v_plain then (case when new.direction = 'in' then 'customer' else 'owner' end) else last_from end,
    last_customer_at = case when new.direction = 'in' and v_plain then new.created_at else last_customer_at end
  where id = new.inquiry_id;
  return new;
end $$;
drop trigger if exists inquiry_message_added on inquiry_messages;
create trigger inquiry_message_added after insert or update of delivery on inquiry_messages for each row execute function inquiry_message_added();
revoke all on function inquiry_message_added() from public, anon, authenticated;

-- Backfill: each old inquiry's message becomes its first message.
insert into inquiry_messages (inquiry_id, direction, source, from_email, body_text, created_at)
  select i.id, 'in', 'form', i.email, i.message, i.created_at from inquiries i
  where not exists (select 1 from inquiry_messages m where m.inquiry_id = i.id);

-- ---------- 4. functions (service role only) ----------
-- A new inquiry from /contact or /wholesale: the conversation, its first
-- message and the "created" event in one transaction.
create or replace function create_inquiry(
  p_topic text, p_subject text, p_name text, p_email text, p_organization text, p_order_number text,
  p_message text, p_customer_id uuid, p_token text, p_ip_hash text
) returns table (id uuid, ref integer)
  language plpgsql security definer set search_path = public as $$
declare v_id uuid; v_ref integer;
begin
  insert into inquiries (topic, subject, name, email, organization, order_number, message, customer_id, token, ip_hash, status, last_customer_at)
    values (p_topic, p_subject, p_name, p_email, p_organization, p_order_number, p_message, p_customer_id, p_token, p_ip_hash, 'new', now())
    returning inquiries.id, inquiries.ref into v_id, v_ref;
  insert into inquiry_messages (inquiry_id, direction, source, from_email, body_text)
    values (v_id, 'in', 'form', p_email, p_message);
  insert into inquiry_events (inquiry_id, action, detail) values (v_id, 'created', p_topic);
  return query select v_id, v_ref;
end $$;

-- A customer email (or an unmatched one the owner attached: p_actor set).
-- Idempotent on the SES message id. A plain reply re-opens a waiting or closed
-- thread (the same move as nextStatus(…, "customer_replied") in
-- lib/inquiries/rules.ts); auto-replies and spam never move the status.
create or replace function record_inbound_message(
  p_inquiry uuid, p_ses_message_id text, p_from text, p_body text, p_full text, p_raw_key text,
  p_email_message_id text, p_flags text[], p_dropped text[], p_attachments jsonb, p_actor uuid default null
) returns text
  language plpgsql security definer set search_path = public as $$
declare v_msg uuid; v_files integer := jsonb_array_length(coalesce(p_attachments, '[]'::jsonb));
begin
  insert into inquiry_messages (inquiry_id, direction, source, from_email, body_text, full_text, raw_key,
                                ses_message_id, email_message_id, flags, dropped_attachments)
    values (p_inquiry, 'in', 'email', p_from, p_body, p_full, p_raw_key, p_ses_message_id, p_email_message_id,
            coalesce(p_flags, '{}'), coalesce(p_dropped, '{}'))
    on conflict (ses_message_id) do nothing
    returning id into v_msg;
  if v_msg is null then return 'duplicate'; end if;
  insert into inquiry_attachments (message_id, filename, content_type, size_bytes, storage_path)
    select v_msg, a->>'filename', a->>'content_type', (a->>'size_bytes')::integer, a->>'storage_path'
    from jsonb_array_elements(coalesce(p_attachments, '[]'::jsonb)) a;
  if v_files > 0 then update inquiries set file_count = file_count + v_files where id = p_inquiry; end if;
  insert into inquiry_events (inquiry_id, action, actor, detail)
    values (p_inquiry, case when p_actor is null then 'customer_replied' else 'unmatched_attached' end, p_actor,
            case when v_files > 0 then v_files || ' attachment' || case when v_files = 1 then '' else 's' end end);
  if not (coalesce(p_flags, '{}') && array['auto_reply','spam']) then
    update inquiries set status = 'needs_reply', waiting_since = null, closed_at = null, closed_by = null
      where id = p_inquiry and status in ('waiting','closed');
  end if;
  return 'recorded';
end $$;

-- Daily (reconcile cron): waiting threads with no reply since p_before close.
create or replace function auto_close_inquiries(p_before timestamptz) returns integer
  language plpgsql security definer set search_path = public as $$
declare v_n integer;
begin
  with closed as (
    update inquiries set status = 'closed', closed_at = now(), closed_by = null, waiting_since = null
      where status = 'waiting' and waiting_since < p_before
      returning id
  )
  insert into inquiry_events (inquiry_id, action) select id, 'auto_closed' from closed;
  get diagnostics v_n = row_count;
  return v_n;
end $$;

revoke all on function create_inquiry(text, text, text, text, text, text, text, uuid, text, text) from public, anon, authenticated;
revoke all on function record_inbound_message(uuid, text, text, text, text, text, text, text[], text[], jsonb, uuid) from public, anon, authenticated;
revoke all on function auto_close_inquiries(timestamptz) from public, anon, authenticated;
grant execute on function create_inquiry(text, text, text, text, text, text, text, uuid, text, text) to service_role;
grant execute on function record_inbound_message(uuid, text, text, text, text, text, text, text[], text[], jsonb, uuid) to service_role;
grant execute on function auto_close_inquiries(timestamptz) to service_role;

-- ---------- 5. files and saved replies ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values ('inquiry-files', 'inquiry-files', false, 10485760, array['image/jpeg','image/png','image/heic','image/heif','application/pdf'])
  on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

insert into saved_replies (name, body) values
  ('Research use only — we can''t advise on use', 'Thanks for asking. Our compounds are sold for laboratory research use only, so we can''t give guidance on preparation, amounts or use. Each lot''s certificate of analysis is on auraprotocols.com/coa if that helps your work.'),
  ('Where''s my order', 'Your order shipped and the tracking link is in your shipping email. If it hasn''t moved in 3 business days, reply here and we''ll open a trace with the carrier.'),
  ('Finding a COA', 'Every lot''s certificate is on auraprotocols.com/coa — enter the lot number printed on the vial label to open its PDF.'),
  ('Wholesale pricing follow-up', 'Thanks for your interest. For volume orders we quote per compound and strength. Could you confirm the compounds, strengths and monthly quantities, and your shipping state?')
  on conflict (name) do nothing;
