// GENERATED by scripts/build-structures.py — do not edit by hand.
// RELATIVE IMPORTS ONLY.

export type StructureSource = "pubchem-3d" | "computed" | "crystal-modeled" | "predicted";
export type Structure = { id: string; label: string; file: string; source: StructureSource;
  heavyAtoms: number; elements: string[]; ref: string; refLabel?: string };

export const STRUCTURES: Record<string, Structure> = {
  "bpc-157": {
    "id": "bpc-157",
    "label": "BPC-157",
    "file": "/structures/bpc-157.sdf",
    "source": "computed",
    "heavyAtoms": 100,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/9941957"
  },
  "tb-500": {
    "id": "tb-500",
    "label": "TB-500",
    "file": "/structures/tb-500.sdf",
    "source": "computed",
    "heavyAtoms": 62,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/62707662"
  },
  "kpv": {
    "id": "kpv",
    "label": "KPV",
    "file": "/structures/kpv.sdf",
    "source": "pubchem-3d",
    "heavyAtoms": 24,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/125672"
  },
  "aod-9604": {
    "id": "aod-9604",
    "label": "AOD-9604",
    "file": "/structures/aod-9604.sdf",
    "source": "computed",
    "heavyAtoms": 126,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/71300630"
  },
  "sermorelin": {
    "id": "sermorelin",
    "label": "Sermorelin",
    "file": "/structures/sermorelin.sdf",
    "source": "computed",
    "heavyAtoms": 236,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/16132413"
  },
  "tesamorelin": {
    "id": "tesamorelin",
    "label": "Tesamorelin",
    "file": "/structures/tesamorelin.sdf",
    "source": "computed",
    "heavyAtoms": 361,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/16137828"
  },
  "igf-1-lr3": {
    "id": "igf-1-lr3",
    "label": "IGF-1 LR3",
    "file": "/structures/igf-1-lr3.sdf",
    "source": "predicted",
    "heavyAtoms": 634,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/substance/381123731"
  },
  "cjc-1295-no-dac": {
    "id": "cjc-1295-no-dac",
    "label": "CJC-1295 (no DAC)",
    "file": "/structures/cjc-1295-no-dac.sdf",
    "source": "computed",
    "heavyAtoms": 238,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/56841945"
  },
  "ipamorelin": {
    "id": "ipamorelin",
    "label": "Ipamorelin",
    "file": "/structures/ipamorelin.sdf",
    "source": "computed",
    "heavyAtoms": 52,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/9831659"
  },
  "ss-31": {
    "id": "ss-31",
    "label": "SS-31",
    "file": "/structures/ss-31.sdf",
    "source": "computed",
    "heavyAtoms": 46,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/11764719"
  },
  "mots-c": {
    "id": "mots-c",
    "label": "MOTS-c",
    "file": "/structures/mots-c.sdf",
    "source": "computed",
    "heavyAtoms": 153,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/146675088"
  },
  "slu-pp-332": {
    "id": "slu-pp-332",
    "label": "SLU-PP-332",
    "file": "/structures/slu-pp-332.sdf",
    "source": "pubchem-3d",
    "heavyAtoms": 22,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/5338394"
  },
  "epithalon": {
    "id": "epithalon",
    "label": "Epithalon",
    "file": "/structures/epithalon.sdf",
    "source": "pubchem-3d",
    "heavyAtoms": 27,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/219042"
  },
  "pinealon": {
    "id": "pinealon",
    "label": "Pinealon",
    "file": "/structures/pinealon.sdf",
    "source": "computed",
    "heavyAtoms": 29,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/10273502"
  },
  "dsip": {
    "id": "dsip",
    "label": "DSIP",
    "file": "/structures/dsip.sdf",
    "source": "computed",
    "heavyAtoms": 60,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/68816"
  },
  "pt-141": {
    "id": "pt-141",
    "label": "PT-141",
    "file": "/structures/pt-141.sdf",
    "source": "computed",
    "heavyAtoms": 74,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/9941379"
  },
  "semax": {
    "id": "semax",
    "label": "Semax",
    "file": "/structures/semax.sdf",
    "source": "computed",
    "heavyAtoms": 57,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/9811102"
  },
  "selank": {
    "id": "selank",
    "label": "Selank",
    "file": "/structures/selank.sdf",
    "source": "computed",
    "heavyAtoms": 53,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/11765600"
  },
  "ghk-cu": {
    "id": "ghk-cu",
    "label": "GHK-Cu",
    "file": "/structures/ghk-cu.sdf",
    "source": "crystal-modeled",
    "heavyAtoms": 25,
    "elements": [
      "C",
      "Cu",
      "N",
      "O"
    ],
    "ref": "https://www.sciencedirect.com/science/article/pii/S002016930082544X"
  },
  "nad-plus": {
    "id": "nad-plus",
    "label": "NAD+",
    "file": "/structures/nad-plus.sdf",
    "source": "pubchem-3d",
    "heavyAtoms": 44,
    "elements": [
      "C",
      "N",
      "O",
      "P"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/5892"
  },
  "glutathione": {
    "id": "glutathione",
    "label": "Glutathione",
    "file": "/structures/glutathione.sdf",
    "source": "pubchem-3d",
    "heavyAtoms": 20,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/124886"
  },
  "semaglutide": {
    "id": "semaglutide",
    "label": "Semaglutide",
    "file": "/structures/semaglutide.sdf",
    "source": "computed",
    "heavyAtoms": 291,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/56843331"
  },
  "tirzepatide": {
    "id": "tirzepatide",
    "label": "Tirzepatide",
    "file": "/structures/tirzepatide.sdf",
    "source": "computed",
    "heavyAtoms": 341,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/166567236"
  },
  "retatrutide": {
    "id": "retatrutide",
    "label": "Retatrutide",
    "file": "/structures/retatrutide.sdf",
    "source": "computed",
    "heavyAtoms": 335,
    "elements": [
      "C",
      "N",
      "O"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/171390338"
  },
  "cagrilintide": {
    "id": "cagrilintide",
    "label": "Cagrilintide",
    "file": "/structures/cagrilintide.sdf",
    "source": "computed",
    "heavyAtoms": 309,
    "elements": [
      "C",
      "N",
      "O",
      "S"
    ],
    "ref": "https://pubchem.ncbi.nlm.nih.gov/compound/171397054"
  }
};

export const STRUCTURE_PANELS: Record<string, string[]> = {
  "bpc-157": [
    "bpc-157"
  ],
  "tb-500": [
    "tb-500"
  ],
  "kpv": [
    "kpv"
  ],
  "aod-9604": [
    "aod-9604"
  ],
  "sermorelin": [
    "sermorelin"
  ],
  "tesamorelin": [
    "tesamorelin"
  ],
  "igf-1-lr3": [
    "igf-1-lr3"
  ],
  "ss-31": [
    "ss-31"
  ],
  "mots-c": [
    "mots-c"
  ],
  "slu-pp-332": [
    "slu-pp-332"
  ],
  "epithalon": [
    "epithalon"
  ],
  "pinealon": [
    "pinealon"
  ],
  "dsip": [
    "dsip"
  ],
  "pt-141": [
    "pt-141"
  ],
  "semax": [
    "semax"
  ],
  "selank": [
    "selank"
  ],
  "ghk-cu": [
    "ghk-cu"
  ],
  "nad-plus": [
    "nad-plus"
  ],
  "glutathione": [
    "glutathione"
  ],
  "semaglutide": [
    "semaglutide"
  ],
  "tirzepatide": [
    "tirzepatide"
  ],
  "retatrutide": [
    "retatrutide"
  ],
  "cagrilintide": [
    "cagrilintide"
  ],
  "cjc-1295-ipamorelin": [
    "cjc-1295-no-dac",
    "ipamorelin"
  ],
  "cagrisema": [
    "cagrilintide",
    "semaglutide"
  ],
  "retatrutide-cagrilintide": [
    "retatrutide",
    "cagrilintide"
  ],
  "bpc-157-tb-500-blend": [
    "bpc-157",
    "tb-500"
  ],
  "bpc-157-tb-500-ghk-cu": [
    "bpc-157",
    "tb-500",
    "ghk-cu"
  ],
  "bpc-157-tb-500-ghk-cu-kpv": [
    "bpc-157",
    "tb-500",
    "ghk-cu",
    "kpv"
  ]
};
