// GENERATED by scripts/fetch-identity.mjs — do not edit by hand.
// Re-run the script; put non-PubChem values in its OVERRIDES with a source URL.
import type { Identity } from "./catalog";

export const IDENTITY: Record<string, Identity> = {
  "bpc-157": {
    "cas": "137525-51-0",
    "formula": "C62H98N16O22",
    "molecularWeight": "1419.5 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/9941957"
  },
  "tb-500": {
    "cas": "885340-08-9",
    "formula": "C38H68N10O14",
    "molecularWeight": "889.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/62707662"
  },
  "semaglutide": {
    "cas": "910463-68-2",
    "formula": "C187H291N45O59",
    "molecularWeight": "4114.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/56843331"
  },
  "tirzepatide": {
    "cas": "2023788-19-2",
    "formula": "C225H348N48O68",
    "molecularWeight": "4813.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/166567236"
  },
  "retatrutide": {
    "cas": "2381089-83-2",
    "formula": "C221H342N46O68",
    "molecularWeight": "4731.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/171390338"
  },
  "cagrilintide": {
    "cas": "1415456-99-3",
    "formula": "C194H312N54O59S2",
    "molecularWeight": "4409.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/171397054"
  },
  "sermorelin": {
    "cas": "86168-78-7",
    "formula": "C149H246N44O42S",
    "molecularWeight": "3357.9 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/16132413"
  },
  "tesamorelin": {
    "cas": "218949-48-5",
    "formula": "C221H366N72O67S",
    "molecularWeight": "5136.0 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/16137828"
  },
  "igf-1-lr3": {
    "cas": "143045-27-6",
    "formula": "C400H625N111O115S9",
    "molecularWeight": "9117.6 g/mol",
    "sequence": "MFPAMPLSSLFVNGPRTLCGAELVDALQFVCGDRGFYFNKPTGYGSSSRRAPQTGIVDECCFRSCDLRRLEMYCAPLKPAKSA",
    "source": "https://pubchem.ncbi.nlm.nih.gov/substance/381123731"
  },
  "kpv": {
    "cas": "67727-97-3",
    "formula": "C16H30N4O4",
    "molecularWeight": "342.4 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/125672"
  },
  "aod-9604": {
    "cas": "221231-10-3",
    "formula": "C78H123N23O23S2",
    "molecularWeight": "1815.1 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/71300630"
  },
  "ss-31": {
    "cas": "736992-21-5",
    "formula": "C32H49N9O5",
    "molecularWeight": "639.8 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/11764719"
  },
  "mots-c": {
    "cas": "1627580-64-6",
    "formula": "C101H152N28O22S2",
    "molecularWeight": "2174.6 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/146675088"
  },
  "slu-pp-332": {
    "cas": "303760-60-3",
    "formula": "C18H14N2O2",
    "molecularWeight": "290.3 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/5338394"
  },
  "epithalon": {
    "cas": "307297-39-8",
    "formula": "C14H22N4O9",
    "molecularWeight": "390.4 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/219042"
  },
  "pinealon": {
    "cas": "175175-23-2",
    "formula": "C15H26N6O8",
    "molecularWeight": "418.4 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/10273502"
  },
  "dsip": {
    "cas": "62568-57-4",
    "formula": "C35H48N10O15",
    "molecularWeight": "848.8 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/68816"
  },
  "pt-141": {
    "cas": "189691-06-3",
    "formula": "C50H68N14O10",
    "molecularWeight": "1025.2 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/9941379"
  },
  "ghk-cu": {
    "cas": "89030-95-5",
    "formula": "C14H23CuN6O4+",
    "molecularWeight": "402.9 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/71587328"
  },
  "nad-plus": {
    "cas": "53-84-9",
    "formula": "C21H27N7O14P2",
    "molecularWeight": "663.4 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/5892"
  },
  "glutathione": {
    "cas": "70-18-8",
    "formula": "C10H17N3O6S",
    "molecularWeight": "307.3 g/mol",
    "source": "https://pubchem.ncbi.nlm.nih.gov/compound/124886"
  }
};
